version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "28017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
